import { useState } from 'react'
import {
  Building2,
  Globe2,
  Phone,
  Image as ImageIcon,
  ShieldCheck,
  Save,
  Upload,
  Check,
  AlertCircle,
  Database,
} from 'lucide-react'
import PageHeader from '../components/common/PageHeader'

// ============================================================
// Initial state (would come from GET /api/settings)
// ============================================================
const INITIAL = {
  name: 'Sayid Mohamed Abdulle International Airport',
  code: 'JUB',
  location: 'Kismayo',
  country: 'Somalia',
  currency: 'USD',
  timezone: 'Africa/Nairobi',
  contact_email: 'finance@jubairport.so',
  contact_phone: '+252 61 555 0100',
  logo_path: null,
  report_footer: 'Generated by AFMS — Airport Financial Management System',
  tax_enabled: true,
  tax_rate: 5.0,
  tax_inclusive: false,
}

const CURRENCIES = [
  { value: 'USD', label: 'USD — US Dollar' },
  { value: 'SOS', label: 'SOS — Somali Shilling' },
  { value: 'KES', label: 'KES — Kenyan Shilling' },
  { value: 'EUR', label: 'EUR — Euro' },
]

const TIMEZONES = [
  { value: 'Africa/Nairobi',   label: 'Africa/Nairobi (EAT, UTC+3)' },
  { value: 'Africa/Mogadishu', label: 'Africa/Mogadishu (EAT, UTC+3)' },
  { value: 'Africa/Addis_Ababa', label: 'Africa/Addis_Ababa (EAT, UTC+3)' },
  { value: 'UTC',              label: 'UTC' },
]

const TABS = [
  { id: 'general',      label: 'General',       icon: Building2 },
  { id: 'localization', label: 'Localization',  icon: Globe2 },
  { id: 'contact',      label: 'Contact',       icon: Phone },
  { id: 'branding',     label: 'Branding',      icon: ImageIcon },
  { id: 'system',       label: 'System',        icon: ShieldCheck },
]

// ============================================================
export default function Settings() {
  const [tab, setTab] = useState('general')
  const [form, setForm] = useState(INITIAL)
  const [saved, setSaved] = useState(false)
  const [error, setError] = useState('')

  const update = (key, value) => {
    setForm((prev) => ({ ...prev, [key]: value }))
    setSaved(false)
  }

  const handleSave = () => {
    setError('')
    setSaved(false)
    if (!form.name.trim()) return setError('Airport name is required.')
    if (!form.code.trim()) return setError('Airport code is required.')
    if (form.tax_enabled && (form.tax_rate < 0 || form.tax_rate > 100)) {
      return setError('Tax rate must be between 0 and 100.')
    }
    // Mock save
    setSaved(true)
    setTimeout(() => setSaved(false), 3000)
  }

  const handleReset = () => {
    setForm(INITIAL)
    setError('')
    setSaved(false)
  }

  return (
    <div className="max-w-[1400px] mx-auto">
      <PageHeader
        title="Settings"
        subtitle="Airport configuration, branding, and system preferences"
        actions={
          <div className="flex items-center gap-2">
            <button
              onClick={handleReset}
              className="text-sm font-medium text-slate-600 hover:text-slate-800 px-3 py-2"
            >
              Reset
            </button>
            <button
              onClick={handleSave}
              className="inline-flex items-center gap-1.5 bg-navy-900 hover:bg-navy-800 text-white text-sm font-medium px-3 py-2 rounded-md transition-colors"
            >
              <Save className="w-4 h-4" />
              Save Changes
            </button>
          </div>
        }
      />

      {/* Alerts */}
      {saved && (
        <div className="flex items-center gap-2 bg-green-50 border border-green-200 text-green-800 text-sm rounded-md px-4 py-3 mb-4">
          <Check className="w-4 h-4" />
          Settings saved successfully (mock — backend will persist).
        </div>
      )}
      {error && (
        <div className="flex items-center gap-2 bg-red-50 border border-red-200 text-red-700 text-sm rounded-md px-4 py-3 mb-4">
          <AlertCircle className="w-4 h-4" />
          {error}
        </div>
      )}

      <div className="flex flex-col lg:flex-row gap-4">
        {/* Tabs sidebar */}
        <aside className="lg:w-56 flex-shrink-0">
          <nav className="bg-white border border-slate-200 rounded-lg p-2 flex lg:flex-col gap-1 overflow-x-auto">
            {TABS.map((t) => {
              const Icon = t.icon
              const active = tab === t.id
              return (
                <button
                  key={t.id}
                  onClick={() => setTab(t.id)}
                  className={`flex items-center gap-2 px-3 py-2 rounded-md text-sm font-medium whitespace-nowrap transition-colors ${
                    active
                      ? 'bg-navy-50 text-navy-900'
                      : 'text-slate-600 hover:bg-slate-50 hover:text-slate-800'
                  }`}
                >
                  <Icon className="w-4 h-4 flex-shrink-0" />
                  {t.label}
                </button>
              )
            })}
          </nav>
        </aside>

        {/* Content */}
        <div className="flex-1 min-w-0">
          <div className="bg-white border border-slate-200 rounded-lg">
            {tab === 'general' && (
              <Section
                title="Airport Information"
                subtitle="Basic identity of the airport authority"
              >
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <Field label="Airport Name" required>
                    <input
                      value={form.name}
                      onChange={(e) => update('name', e.target.value)}
                      className="w-full px-3 py-2 text-sm border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-navy-800"
                    />
                  </Field>
                  <Field label="Airport Code (IATA/ICAO)" required>
                    <input
                      value={form.code}
                      onChange={(e) => update('code', e.target.value.toUpperCase())}
                      maxLength={6}
                      className="w-full px-3 py-2 text-sm border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-navy-800 font-mono uppercase"
                    />
                  </Field>
                  <Field label="Location / City">
                    <input
                      value={form.location}
                      onChange={(e) => update('location', e.target.value)}
                      className="w-full px-3 py-2 text-sm border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-navy-800"
                    />
                  </Field>
                  <Field label="Country">
                    <input
                      value={form.country}
                      onChange={(e) => update('country', e.target.value)}
                      className="w-full px-3 py-2 text-sm border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-navy-800"
                    />
                  </Field>
                </div>
              </Section>
            )}

            {tab === 'localization' && (
              <Section
                title="Localization"
                subtitle="Currency and timezone used across all reports"
              >
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <Field label="Currency">
                    <select
                      value={form.currency}
                      onChange={(e) => update('currency', e.target.value)}
                      className="w-full px-3 py-2 text-sm border border-slate-300 rounded-md bg-white focus:outline-none focus:ring-2 focus:ring-navy-800"
                    >
                      {CURRENCIES.map((c) => (
                        <option key={c.value} value={c.value}>{c.label}</option>
                      ))}
                    </select>
                  </Field>
                  <Field label="Timezone">
                    <select
                      value={form.timezone}
                      onChange={(e) => update('timezone', e.target.value)}
                      className="w-full px-3 py-2 text-sm border border-slate-300 rounded-md bg-white focus:outline-none focus:ring-2 focus:ring-navy-800"
                    >
                      {TIMEZONES.map((t) => (
                        <option key={t.value} value={t.value}>{t.label}</option>
                      ))}
                    </select>
                  </Field>
                </div>

                <div className="mt-6 pt-6 border-t border-slate-200">
                  <h4 className="text-sm font-semibold text-slate-700 mb-3">Tax Configuration</h4>
                  <label className="flex items-center gap-3 mb-4">
                    <input
                      type="checkbox"
                      checked={form.tax_enabled}
                      onChange={(e) => update('tax_enabled', e.target.checked)}
                      className="w-4 h-4 rounded border-slate-300 text-navy-900 focus:ring-navy-800"
                    />
                    <span className="text-sm text-slate-700">
                      Enable automatic tax on transactions
                    </span>
                  </label>

                  {form.tax_enabled && (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <Field label="Tax Rate (%)">
                        <input
                          type="number"
                          step="0.01"
                          min="0"
                          max="100"
                          value={form.tax_rate}
                          onChange={(e) => update('tax_rate', Number(e.target.value))}
                          className="w-full px-3 py-2 text-sm border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-navy-800 tabular-nums"
                        />
                      </Field>
                      <Field label="Tax Mode">
                        <select
                          value={form.tax_inclusive ? 'inclusive' : 'exclusive'}
                          onChange={(e) => update('tax_inclusive', e.target.value === 'inclusive')}
                          className="w-full px-3 py-2 text-sm border border-slate-300 rounded-md bg-white focus:outline-none focus:ring-2 focus:ring-navy-800"
                        >
                          <option value="exclusive">Exclusive — added on top of subtotal</option>
                          <option value="inclusive">Inclusive — included in displayed amounts</option>
                        </select>
                      </Field>
                    </div>
                  )}
                </div>
              </Section>
            )}

            {tab === 'contact' && (
              <Section
                title="Contact Information"
                subtitle="Shown on exported reports and invoices"
              >
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <Field label="Contact Email">
                    <input
                      type="email"
                      value={form.contact_email}
                      onChange={(e) => update('contact_email', e.target.value)}
                      className="w-full px-3 py-2 text-sm border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-navy-800"
                    />
                  </Field>
                  <Field label="Contact Phone">
                    <input
                      value={form.contact_phone}
                      onChange={(e) => update('contact_phone', e.target.value)}
                      className="w-full px-3 py-2 text-sm border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-navy-800 font-mono"
                    />
                  </Field>
                </div>
                <div className="mt-4">
                  <Field label="Report Footer Text">
                    <input
                      value={form.report_footer}
                      onChange={(e) => update('report_footer', e.target.value)}
                      className="w-full px-3 py-2 text-sm border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-navy-800"
                    />
                  </Field>
                  <p className="text-xs text-slate-500 mt-1">
                    Appears at the bottom of every PDF and printed report.
                  </p>
                </div>
              </Section>
            )}

            {tab === 'branding' && (
              <Section
                title="Branding"
                subtitle="Logo and visual identity used on reports"
              >
                <div className="flex flex-col sm:flex-row items-start gap-6">
                  <div className="w-32 h-32 rounded-lg border-2 border-dashed border-slate-300 bg-slate-50 flex flex-col items-center justify-center flex-shrink-0">
                    <ImageIcon className="w-8 h-8 text-slate-300" />
                    <p className="text-[10px] text-slate-400 mt-1">No logo</p>
                  </div>
                  <div className="flex-1">
                    <p className="text-sm font-medium text-slate-700 mb-1">
                      Airport / Authority Logo
                    </p>
                    <p className="text-xs text-slate-500 mb-3">
                      PNG, JPG, or SVG. Recommended size 400×120, max 1 MB. Appears on all
                      exported PDF reports and the login page.
                    </p>
                    <button className="inline-flex items-center gap-1.5 text-sm font-medium text-navy-900 border border-navy-200 bg-navy-50 hover:bg-navy-100 px-3 py-2 rounded-md">
                      <Upload className="w-4 h-4" />
                      Upload Logo
                    </button>
                    <p className="text-xs text-slate-400 mt-2">
                      Upload handling requires the backend. This is a placeholder.
                    </p>
                  </div>
                </div>
              </Section>
            )}

            {tab === 'system' && (
              <Section
                title="System Information"
                subtitle="Runtime info and database maintenance"
              >
                <div className="space-y-3">
                  <InfoRow label="Application" value="AFMS — Airport Financial Management System" />
                  <InfoRow label="Version" value="1.0.0 (demo)" />
                  <InfoRow label="Backend" value="Flask 3.x + SQLAlchemy (SQLite)" />
                  <InfoRow label="Frontend" value="React 19 + Vite + Tailwind CSS 3" />
                  <InfoRow label="Database Path" value="backend/instance/airport.db" mono />
                  <InfoRow label="Default Currency" value={form.currency} />
                  <InfoRow label="Default Timezone" value={form.timezone} />
                </div>

                <div className="mt-6 pt-6 border-t border-slate-200">
                  <div className="flex items-start gap-3 bg-amber-50 border border-amber-200 rounded-md px-4 py-3">
                    <Database className="w-4 h-4 text-amber-600 mt-0.5 flex-shrink-0" />
                    <div className="flex-1">
                      <p className="text-sm font-medium text-amber-800">Database Backup</p>
                      <p className="text-xs text-amber-700 mt-0.5">
                        Create a point-in-time backup of the SQLite database. Backups are stored
                        privately and are not publicly accessible.
                      </p>
                      <button
                        onClick={() => alert('Would create backup:\nairport_backup_YYYY_MM_DD.db')}
                        className="mt-2 inline-flex items-center gap-1.5 text-xs font-medium text-white bg-amber-600 hover:bg-amber-700 px-3 py-1.5 rounded-md"
                      >
                        <Database className="w-3.5 h-3.5" />
                        Create Backup Now
                      </button>
                    </div>
                  </div>
                </div>
              </Section>
            )}
          </div>
        </div>
      </div>

      <p className="text-xs text-slate-400 text-center pt-4">
        ⚠️ Demo — real settings will load from <code className="font-mono">GET /api/settings</code> and save via{' '}
        <code className="font-mono">PUT /api/settings</code> once the backend is connected.
      </p>
    </div>
  )
}

// ============================================================
function Section({ title, subtitle, children }) {
  return (
    <div className="p-6">
      <div className="mb-5">
        <h3 className="text-base font-semibold text-slate-800">{title}</h3>
        {subtitle && <p className="text-xs text-slate-500 mt-0.5">{subtitle}</p>}
      </div>
      {children}
    </div>
  )
}

function Field({ label, required, children }) {
  return (
    <div>
      <label className="block text-xs font-medium text-slate-600 mb-1">
        {label} {required && <span className="text-red-600">*</span>}
      </label>
      {children}
    </div>
  )
}

function InfoRow({ label, value, mono }) {
  return (
    <div className="flex items-start justify-between gap-4 border-b border-slate-100 pb-2 last:border-b-0">
      <span className="text-xs font-medium text-slate-500 uppercase tracking-wide pt-0.5">
        {label}
      </span>
      <span className={`text-sm text-slate-800 text-right ${mono ? 'font-mono text-xs' : ''}`}>
        {value}
      </span>
    </div>
  )
}